### ISSUE TITLE
Botão fechar dos Dialogs não fecha as janelas

### ISSUE THREAD

**Issue by eduardoweiland** [brunopick/SIMULA#14]
Só clicando em cancelar elas são fechadas. Clicar no botão fechar deveria ter o mesmo comportamento de cancelar.

**Comment by brunopick** [comment]
A alteração feita para alterar o Look&Feel e utilizar os components swing no lugar do AWT fez com que os eventos de fechar dialogs tivessem o efeito esperado que é fechar o dialog. Então estou fechando o issue pois isso já não ocorre mais.
