### ISSUE TITLE
Verificar comportamento da ação atinge_agente

### ISSUE THREAD

**Issue by eduardoweiland** [brunopick/SIMULA#21]
No exemplo abaixo, os meteoros só se movem na direção S. Como é possível visualizar na primeira imagem, nenhum meteoro irá atingir a nave. Entretanto, a segunda imagem mostra que houve colisão entre a nave e o meteoro, sendo que eles não estavam em rota de colisão.

![ciclo_13](https://cloud.githubusercontent.com/assets/1799015/11285650/c7aa31da-8ef7-11e5-934b-094039c2356c.png)
![ciclo_14](https://cloud.githubusercontent.com/assets/1799015/11285648/c76c1f94-8ef7-11e5-9d39-cbc43ff77ec7.png)

**Comment by brunopick** [comment]
Comportamento da ação foi verificado e funciona da seguinte maneira:
Se for possível perceber um agente num raio de 1 unidade de distância então ele pode ser atingido.

Com isso é possível verificar que a ação atinge_agente não é confirmado ao 'mover-se' para a posição do outro agente, mas sim ao 'perceber'.
